In [ ]:
import os
import pandas as pd


klasor_yolu = "C:/iDeal/data"

dataframes = []

# Klasördeki tüm dosyaları listele ve txt dosyalarını seç
for dosya in os.listdir(klasor_yolu):
    if dosya.endswith('.txt'):  # Sadece .txt uzantılı dosyaları seç
        dosya_yolu = os.path.join(klasor_yolu, dosya)
        
        # Dosyayı oku (burada delimiter ve diğer parametreleri ayarlayabilirsiniz)
        df = pd.read_csv(
            dosya_yolu,
            delimiter=';',   # Noktalı virgül ile ayrıldığını varsayıyoruz
            decimal=',',     # Ondalık ayırıcı olarak virgül kullanılıyor
            header=None,     # Eğer sütun başlıkları yoksa
            names=['Tarih', 'Saat', 'Açılış', 'Yüksek', 'Düşük', 'Kapanış', 'Hacim']  # Sütun isimleri
        )
        
       
        df['Hisse'] = dosya[6:-7]
        
        # Listeye ekle
        dataframes.append(df)
        print(f"{dosya} verisi başarıyla okundu.")

# Tüm DataFrame'leri birleştir
tum_veri = pd.concat(dataframes, ignore_index=True)

# Tarih ve Saat sütunlarını birleştirip datetime formatına çevir, ardından indeks olarak ayarla
tum_veri['Datetime'] = pd.to_datetime(tum_veri['Tarih'] + ' ' + tum_veri['Saat'], format='%d.%m.%Y %H:%M')
tum_veri=tum_veri.set_index('Datetime', inplace=True)
tum_veri=tum_veri.drop(['Tarih', 'Saat'], axis=1, inplace=True)




tum_veri.to_csv("C:/iDeal/data/birlesik_veri.csv")

In [12]:
tum_veri

                     Açılış  Yüksek  Düşük  Kapanış     Hacim  Hisse
Datetime
2023-06-15 09:00:00   27.50   27.50  27.50    27.50    666490  A1CAP
2023-06-15 10:00:00   27.50   27.50  27.50    27.50   2731575  A1CAP
2023-06-15 11:00:00   27.50   27.50  27.50    27.50   1144028  A1CAP
2023-06-15 12:00:00   27.50   27.50  27.50    27.50    650898  A1CAP
2023-06-15 13:00:00   27.50   27.50  27.50    27.50    578215  A1CAP
...                     ...     ...    ...      ...       ...    ...
2024-12-06 14:00:00   14.13   14.17  14.08    14.08   3349109  ZRGYO
2024-12-06 15:00:00   14.09   14.14  14.04    14.14   7197891  ZRGYO
2024-12-06 16:00:00   14.14   14.14  14.04    14.06   5277869  ZRGYO
2024-12-06 17:00:00   14.07   14.07  13.85    13.95  13452290  ZRGYO
2024-12-06 18:00:00   14.04   14.04  14.04    14.04   1171020  ZRGYO

[11362625 rows x 6 columns]